services:
  postgres:
    container_name: clocess_db
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: clocess_redis
    image: redis:latest
    volumes:
      - ./backend/cache/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
      - ./backend/logs/redis-logs:/redis-logs
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}

  backend:
    container_name: clocess_backend
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  frontend:
    container_name: clocess_frontend
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: ${BESZEL_URL}
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      TOKEN: ${BESZEL_TOKEN}
      KEY: ${BESZEL_KEY}

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle_data:/data
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_AUTH_PROVIDER=simple

volumes:
  pgdata:
  redis-data:
