services:
  postgres:
    ports:
      - "127.0.0.1:[host_port]:[container_port]"
    restart: unless-stopped

  redis:
    ports:
      - "127.0.0.1:[host_port]:[container_port]"
    restart: unless-stopped

  backend:
    ports:
      - "127.0.0.1:[host_port]:[container_port]"
    restart: unless-stopped

  frontend:
    ports:
      - "127.0.0.1:[host_port]:[container_port]"
    restart: unless-stopped

  landing:
    ports:
      - "[host_port]:[container_port]"
    restart: unless-stopped

  beszel:
    ports:
      - "[host_port]:[container_port]"
    restart: unless-stopped

  dozzle:
    ports:
      - "[host_port]:[container_port]"
    restart: unless-stopped
