// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"
)

const createFileRecord = `-- name: CreateFileRecord :one
insert into files (id, user_id, filename, file_type, disk_path, remote_id)
  values ($1, $2, $3, $4, $5, $6)
  returning id
`

type CreateFileRecordParams struct {
	ID       int32  `json:"id"`
	UserID   int32  `json:"user_id"`
	Filename string `json:"filename"`
	FileType string `json:"file_type"`
	DiskPath string `json:"disk_path"`
	RemoteID int32  `json:"remote_id"`
}

func (q *Queries) CreateFileRecord(ctx context.Context, arg CreateFileRecordParams) (int32, error) {
	row := q.db.QueryRow(ctx, createFileRecord,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.FileType,
		arg.DiskPath,
		arg.RemoteID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteFile = `-- name: DeleteFile :one
delete from files where id = $1 and user_id = $2
returning filename
`

type DeleteFileParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteFile, arg.ID, arg.UserID)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}

const getAllUserFiles = `-- name: GetAllUserFiles :many
select id, filename, file_type from files where user_id = $1
`

type GetAllUserFilesRow struct {
	ID       int32  `json:"id"`
	Filename string `json:"filename"`
	FileType string `json:"file_type"`
}

func (q *Queries) GetAllUserFiles(ctx context.Context, userID int32) ([]GetAllUserFilesRow, error) {
	rows, err := q.db.Query(ctx, getAllUserFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserFilesRow
	for rows.Next() {
		var i GetAllUserFilesRow
		if err := rows.Scan(&i.ID, &i.Filename, &i.FileType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileName = `-- name: GetFileName :one
select filename from files where id = $1 and user_id = $2
`

type GetFileNameParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetFileName(ctx context.Context, arg GetFileNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getFileName, arg.ID, arg.UserID)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}

const getNextFileID = `-- name: GetNextFileID :one
select nextval('files_id_seq')::int
`

func (q *Queries) GetNextFileID(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextFileID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
