// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remotes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRemoteSecret = `-- name: CreateRemoteSecret :one
INSERT into remote_secrets(remote_id, encrypted_private_key, key_version)
  values ($1, $2, $3)
  returning id
`

type CreateRemoteSecretParams struct {
	RemoteID            pgtype.Int4 `json:"remote_id"`
	EncryptedPrivateKey []byte      `json:"encrypted_private_key"`
	KeyVersion          int16       `json:"key_version"`
}

func (q *Queries) CreateRemoteSecret(ctx context.Context, arg CreateRemoteSecretParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRemoteSecret, arg.RemoteID, arg.EncryptedPrivateKey, arg.KeyVersion)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRemoteSecret = `-- name: GetRemoteSecret :many
SELECT remote_id, encrypted_private_key, key_version FROM remote_secrets where remote_id = $1
`

type GetRemoteSecretRow struct {
	RemoteID            pgtype.Int4 `json:"remote_id"`
	EncryptedPrivateKey []byte      `json:"encrypted_private_key"`
	KeyVersion          int16       `json:"key_version"`
}

func (q *Queries) GetRemoteSecret(ctx context.Context, remoteID pgtype.Int4) ([]GetRemoteSecretRow, error) {
	rows, err := q.db.Query(ctx, getRemoteSecret, remoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRemoteSecretRow
	for rows.Next() {
		var i GetRemoteSecretRow
		if err := rows.Scan(&i.RemoteID, &i.EncryptedPrivateKey, &i.KeyVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
