// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remotes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRemote = `-- name: CreateRemote :one
INSERT into remotes(user_id, host, port, username, base_path, public_key, host_key_fingerprint)
  values ($1, $2, $3, $4, $5, $6, $7)
  returning id
`

type CreateRemoteParams struct {
	UserID             int32       `json:"user_id"`
	Host               string      `json:"host"`
	Port               int32       `json:"port"`
	Username           string      `json:"username"`
	BasePath           string      `json:"base_path"`
	PublicKey          string      `json:"public_key"`
	HostKeyFingerprint pgtype.Text `json:"host_key_fingerprint"`
}

func (q *Queries) CreateRemote(ctx context.Context, arg CreateRemoteParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRemote,
		arg.UserID,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.BasePath,
		arg.PublicKey,
		arg.HostKeyFingerprint,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createRemoteSecret = `-- name: CreateRemoteSecret :one
INSERT into remote_secrets(remote_id, encrypted_private_key, key_version)
  values ($1, $2, $3)
  returning id
`

type CreateRemoteSecretParams struct {
	RemoteID            pgtype.Int4 `json:"remote_id"`
	EncryptedPrivateKey []byte      `json:"encrypted_private_key"`
	KeyVersion          int16       `json:"key_version"`
}

func (q *Queries) CreateRemoteSecret(ctx context.Context, arg CreateRemoteSecretParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRemoteSecret, arg.RemoteID, arg.EncryptedPrivateKey, arg.KeyVersion)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deactivateUserRemote = `-- name: DeactivateUserRemote :execrows
WITH deleted_secret AS (
    DELETE FROM remote_secrets
    WHERE remote_secrets.remote_id IN (
        SELECT remotes.id FROM remotes WHERE remotes.id = $1 AND remotes.user_id = $2
    )
)
UPDATE remotes
SET active = false
WHERE remotes.id = $1 AND remotes.user_id = $2
`

type DeactivateUserRemoteParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeactivateUserRemote(ctx context.Context, arg DeactivateUserRemoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateUserRemote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserRemote = `-- name: DeleteUserRemote :execrows
DELETE FROM remotes WHERE id = $1 AND user_id = $2
`

type DeleteUserRemoteParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteUserRemote(ctx context.Context, arg DeleteUserRemoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserRemote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllUserRemotes = `-- name: GetAllUserRemotes :many
SELECT id, host, port, username, base_path FROM remotes WHERE user_id = $1
`

type GetAllUserRemotesRow struct {
	ID       int32  `json:"id"`
	Host     string `json:"host"`
	Port     int32  `json:"port"`
	Username string `json:"username"`
	BasePath string `json:"base_path"`
}

func (q *Queries) GetAllUserRemotes(ctx context.Context, userID int32) ([]GetAllUserRemotesRow, error) {
	rows, err := q.db.Query(ctx, getAllUserRemotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserRemotesRow
	for rows.Next() {
		var i GetAllUserRemotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.BasePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemoteSecret = `-- name: GetRemoteSecret :many
SELECT remote_id, encrypted_private_key, key_version FROM remote_secrets where remote_id = $1
`

type GetRemoteSecretRow struct {
	RemoteID            pgtype.Int4 `json:"remote_id"`
	EncryptedPrivateKey []byte      `json:"encrypted_private_key"`
	KeyVersion          int16       `json:"key_version"`
}

func (q *Queries) GetRemoteSecret(ctx context.Context, remoteID pgtype.Int4) ([]GetRemoteSecretRow, error) {
	rows, err := q.db.Query(ctx, getRemoteSecret, remoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRemoteSecretRow
	for rows.Next() {
		var i GetRemoteSecretRow
		if err := rows.Scan(&i.RemoteID, &i.EncryptedPrivateKey, &i.KeyVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRemotes = `-- name: GetUserRemotes :many
SELECT id, host, port, username, base_path FROM remotes WHERE user_id = $1 and active=true
`

type GetUserRemotesRow struct {
	ID       int32  `json:"id"`
	Host     string `json:"host"`
	Port     int32  `json:"port"`
	Username string `json:"username"`
	BasePath string `json:"base_path"`
}

func (q *Queries) GetUserRemotes(ctx context.Context, userID int32) ([]GetUserRemotesRow, error) {
	rows, err := q.db.Query(ctx, getUserRemotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRemotesRow
	for rows.Next() {
		var i GetUserRemotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.BasePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
